name: 'Operate K6 CRD'
description: 'Create and delete K6 Custom Resource Definitions to Kubernetes Cluster'
author: 'ymktmk'
branding:
  icon: 'k6'
  color: 'orange'
inputs:
  vus:
    description: 'vus'
    required: false
    default: ''
  duration: 
    description: 'duration'
    required: false
    default: ''
  rps:
    description: 'rps'
    required: false
    default: ''
  parallelism: 
    description: 'parallelism'
    required: false
    default: ''
  file: 
    description: 'scenario javaScript file'
    required: false
    default: ''
  template:
    description: 'k6 template file path'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    
    - name: Clone
      shell: bash
      run: |
        wget -nv https://github.com/ymktmk/operate-k6-crd/releases/download/v${{inputs.version}}/operate-k6-crd_${{inputs.version}}_linux_amd64.tar.gz
        tar xvf operate-k6-crd_${{inputs.version}}_linux_amd64.tar.gz

    - name: Build & Run
      shell: bash
      run: ./operate-k6-crd
      env:
        INPUT_VUS: ${{ inputs.vus }}
        INPUT_DURATION: ${{ inputs.duration }}
        INPUT_RPS: ${{ inputs.rps }}
        INPUT_PARALLELISM: ${{ inputs.parallelism }}
        INPUT_FILE: ${{ inputs.file }}
        INPUT_TEMPLATE: ${{ inputs.template }}
