name: 'Operate K6 CRD'
description: 'Create and delete K6 Custom Resource Definitions to Kubernetes Cluster'
author: 'ymktmk'
runs:
  using: 'composite'
  steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: build & run
      shell: bash
      run: go run main.go
      env:
        INPUT_METHOD: ${{ inputs.method }}
        INPUT_VUS: ${{ inputs.vus }}
        INPUT_DURATION: ${{ inputs.duration }}
        INPUT_RPS: ${{ inputs.rps }}
        INPUT_PARALLELISM: ${{ inputs.parallelism }}
        INPUT_TEMPLATE: ${{ inputs.template }}
branding:
  icon: 'k6'
  color: 'orange'
inputs:
  method:
    description: 'set create or delete'
    required: true
  vus:
    description: 'vus'
    required: false
    default: ''
  duration: 
    description: 'duration'
    required: false
    default: ''
  rps:
    description: 'rps'
    required: false
    default: ''
  parallelism: 
    description: 'parallelism'
    required: false
    default: ''
  template:
    description: 'k6 template file path'
    required: true
